Fix capitalization typo error which causes runtime error in some *nix machines
ramsaylanier/wordexpress-schema pull request #21
Opened 2018-02-28 04:33 UTC by iamake

Below is an error on my environment. Patching this PR would fix the problem.

```
[ec2-user@ip-172-26-7-xxx xxx-graph]$ uname -a
Linux ip-172-26-7-xxx 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@ip-172-26-7-xxx xxx-graph]$ ./pm2-app.sh 
module.js:559
    throw err;
    ^

Error: Cannot find module './modules/Postmeta/connectors'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/...xxx.../node_modules/wordexpress-schema/lib/db.js:39:20)
```

2018-02-28 14:18 UTC, ramsaylanier requested changes

2018-02-28 14:18 UTC, ramsaylanier commented on src/db.js
> +import PostmetaConnectors from './modules/PostMeta/connectors'
I think for this we should just rename the directory to `Postmeta` to be consistent.

2018-02-28 14:23 UTC, ramsaylanier commented
Also it looks like some commits from the previous PR are still in here. Did you pull from the upstream before submitting this PR?

2018-03-01 00:16 UTC, closed without merging

2018-03-01 00:16 UTC, iamake commented
Will close this for another one

2018-03-01 01:16 UTC, iamake commented
#22 created to replace this one